# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requisitos', '0010_auto_20171202_2106'),
        ('projecto', '0003_projecto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='cambio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('referencia', models.CharField(max_length=150)),
                ('revisado_por', models.CharField(max_length=150)),
                ('fecha_revision', models.DateTimeField()),
                ('aprovado_por', models.CharField(max_length=150)),
                ('fecha_aprovacion', models.DateTimeField()),
                ('proponente', models.CharField(max_length=150)),
                ('cambio', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projecto.Projecto')),
                ('responsable', models.ManyToManyField(blank=True, to='requisitos.actor')),
            ],
        ),
    ]
