# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='para',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='por',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projecto',
            name='version',
            field=models.IntegerField(),
        ),
    ]
