# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0002_auto_20171112_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecto',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
