# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projecto', '0002_auto_20171112_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('fuentes', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projecto.Projecto')),
            ],
        ),
    ]
