# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projecto', '0002_auto_20171112_1849'),
        ('requisitos', '0005_requisito_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisito_restriccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('fuentes', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('importancia', models.CharField(choices=[('PD', 'PD'), ('Importante', 'Importante'), ('Vital', 'Vital')], default='PD', max_length=15)),
                ('urgencia', models.CharField(choices=[('PD', 'PD'), ('Importante', 'Importante'), ('Vital', 'Vital')], default='PD', max_length=15)),
                ('estado', models.CharField(choices=[('PD', 'PD'), ('Importante', 'Importante'), ('Vital', 'Vital')], default='PD', max_length=15)),
                ('estabilidad', models.CharField(choices=[('PD', 'PD'), ('Importante', 'Importante'), ('Vital', 'Vital')], default='PD', max_length=15)),
                ('comentario', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autores', models.ManyToManyField(blank=True, to='requisitos.actor')),
                ('dependencias', models.ManyToManyField(blank=True, to='requisitos.objetivo')),
                ('projecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projecto.Projecto')),
            ],
        ),
    ]
